### PR TITLE
Adding groups to users

### PR DESCRIPTION
**Pull request by ggalves**
With this change we are now able to set permissions on projects by LDAP groups.

### CODE REVIEW

**Review by woowahan-jaehoon — COMMENTED** [review]
Why didn't reuse result of `userGroups` method?

`userGroups` method can be called twice in `getUser` and `isMemberOfGroups` both.

**Comment by woowahan-jaehoon** [comment]
> Why didn't reuse result of `userGroups` method?
> 
> `userGroups` method can be called twice in `getUser` and `isMemberOfGroups` both.

Nevermind

**Comment by eyalbenivri** [comment]
Hey - Sorry for responding late.
Am i wrong, or in case the user is not in the "allowed" groups, the user can still login and no exception will be thrown?

**Comment by ggalves** [comment]
Hey, @eyalbenivri 
I don't really remember that code anymore, but I think this will check if user is in allowed groups.
```            
if (!isMemberOfGroups(connection, entry, ldapAllowedGroups)) {
    throw new UserManagerException("User is not member of allowed groups");
}
```
Actually, this is not part of my PR, I just extracted the code from `isMemberOfGroup` and created a new function (`userGroups`), where I made some changes to get user groups. The `isMemberOfGroup` function still works the same way, I just changed it to remove duplicity

**Comment by woowahan-jaehoon** [comment]
I already use this PR with some modification because conflict with #17. 
(bb803852)

This PR works correctly.

**Comment by woowahan-jaehoon** [comment]
Could I modifiy this PR for resolving conflict?

**Comment by ggalves** [comment]
@woowahan-jaehoon I would be grateful :)

**Comment by woowahan-jaehoon** [comment]
Sorry, but I'm late.

I fetched this PR and rebased from current master.
But I cannot push that in ggalves:user-groups branch because this branch is in @ggalves's repository.
So I pushed rebased-branch to woowahan-jaehoon:ggalves-user-groups-rebase temporary.
(https://github.com/woowahan-jaehoon/azkaban-ldap-usermanager/tree/ggalves-user-groups-rebase)
(You can see diff in woowahan-jaehoon/azkaban-ldap-usermanager@1643c8f )


I think that there are some options for rebase this PR.

1. @ggalves give me write permission to @ggalves' repository.
   This case, I will push rebased-branch to ggalves:user-groups .
2. Create another PR.
   This case, I will create PR about woowahan-jaehoon:ggalves-user-groups-rebase

Which option is better?

**Comment by ggalves** [comment]
hey @woowahan-jaehoon 

feel free to do what you think it is easier for you.

If you choose the first option, I invited you to be a collaborator on my forked repository. But no problem for me if you wanna go with the second option :)

**Comment by woowahan-jaehoon** [comment]
I think that first option is better because this PR can be remain. :)

Thank you for invite me.
I pushed and backuped up your original commit to https://github.com/woowahan-jaehoon/azkaban-ldap-usermanager/tree/ggalves-user-groups.

**Pull request closed without merging**
